import { defineConfig } from 'vitepress'

export default defineConfig({
  lang: 'id-ID',
  title: 'Kenanga Admin',
  description: 'Panduan starter kit dashboard Laravel Blade berbasis komponen.',
  cleanUrls: true,
  appearance: 'dark',
  head: [['meta', { name: 'theme-color', content: '#09090b' }]],
  themeConfig: {
    siteTitle: 'Kenanga / Docs',
    nav: [
      { text: 'Mulai', link: '/panduan/mulai' },
      { text: 'Komponen', link: '/komponen/' },
      { text: 'Integrasi backend', link: '/integrasi/' },
    ],
    sidebar: [
      {
        text: '📖 Panduan',
        items: [
          { text: '🏠 Pengantar', link: '/' },
          { text: '🚀 Instalasi & menjalankan', link: '/panduan/mulai' },
          { text: '🧩 Struktur & Blade', link: '/panduan/struktur' },
          { text: '🧭 Halaman & navigasi', link: '/panduan/halaman' },
          { text: '🎨 Tema & aset', link: '/panduan/tema' },
        ],
      },
      {
        text: '🧰 Komponen',
        items: [
          { text: '🧰 Peta komponen', link: '/komponen/' },
          { text: '🧱 Tata letak & tampilan', link: '/komponen/tampilan' },
          { text: '📝 Form & input', link: '/komponen/form' },
          { text: '📋 Tabel & status', link: '/komponen/tabel' },
          { text: '📊 Grafik & statistik', link: '/komponen/grafik' },
          { text: '💬 Umpan balik & dialog', link: '/komponen/umpan-balik' },
          { text: '⚡ Interaksi JavaScript', link: '/komponen/interaksi' },
          { text: '🧰 Pola data baru', link: '/komponen/pola-data' },
          { text: '📢 Alert', link: '/komponen/alert' },
          { text: '🏷️ Badge', link: '/komponen/badge' },
          { text: '🔘 Button', link: '/komponen/button' },
          { text: '🗂️ Card', link: '/komponen/card' },
          { text: '📈 Chart', link: '/komponen/chart' },
          { text: '🔎 Combobox', link: '/komponen/combobox' },
          { text: '📅 Date range', link: '/komponen/date-range' },
          { text: '🗄️ Drawer', link: '/komponen/drawer' },
          { text: '🔎 Filter bar', link: '/komponen/filter-bar' },
          { text: '📑 Detail list', link: '/komponen/detail-list' },
          { text: '🕒 Timeline', link: '/komponen/timeline' },
          { text: '🗂️ Tabs', link: '/komponen/tabs' },
          { text: '🛡️ Confirm action', link: '/komponen/confirm-action' },
          { text: '📭 Empty', link: '/komponen/empty' },
          { text: '🧷 Field', link: '/komponen/field' },
          { text: '📎 File preview', link: '/komponen/file-preview' },
          { text: '🧿 Icon', link: '/komponen/icon' },
          { text: '⌨️ Input', link: '/komponen/input' },
          { text: '🪟 Modal', link: '/komponen/modal' },
          { text: '📰 Page header', link: '/komponen/page-header' },
          { text: '📄 Pagination', link: '/komponen/pagination' },
          { text: '🔽 Select', link: '/komponen/select' },
          { text: '📊 Stat card', link: '/komponen/stat-card' },
          { text: '🔀 Switch', link: '/komponen/switch' },
          { text: '📋 Table state', link: '/komponen/table-state' },
          { text: '📝 Textarea', link: '/komponen/textarea' },
        ],
      },
      {
        text: '🔌 Integrasi Laravel',
        items: [
          { text: '🔌 Peta integrasi', link: '/integrasi/' },
          { text: '🗃️ Data & halaman CRUD', link: '/integrasi/crud' },
          { text: '📝 Form, validasi & unggah', link: '/integrasi/form' },
          { text: '📊 Tabel & grafik dari server', link: '/integrasi/data' },
          { text: '🔐 Autentikasi & produksi', link: '/integrasi/auth' },
        ],
      },
    ],
    outline: { level: [2, 3], label: 'Di halaman ini' },
    search: { provider: 'local', options: { translations: {
      button: { buttonText: 'Cari dokumentasi', buttonAriaLabel: 'Cari dokumentasi' },
      modal: {
        noResultsText: 'Tidak ada hasil', resetButtonTitle: 'Hapus pencarian',
        footer: { selectText: 'pilih', navigateText: 'navigasi', closeText: 'tutup' },
      },
    } } },
    docFooter: { prev: 'Sebelumnya', next: 'Selanjutnya' },
    returnToTopLabel: 'Kembali ke atas',
    sidebarMenuLabel: 'Menu',
    darkModeSwitchLabel: 'Tema',
    lastUpdated: { text: 'Terakhir diperbarui' },
  },
})
